### PR TITLE
Support Security Group Name

### PR DESCRIPTION
**Pull request by GnatorX**
* sg name field in crd

* add implementation

* Move to getsgforVPC, move SG names into SG, unique items validation

---------

Issue #, if available: https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/20

Description of changes:
Add support for Security group names
Continuation of https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/408

Credit: Most of the code was implemented by @abeer-stripe

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sushrk** [comment]
Thanks @GnatorX, I'm taking a look at the PR. 

Few initial thoughts: 
Can we merge this into a feature branch so I can work on testing this internally before release? 

[expiration cache](https://github.com/kubernetes/client-go/blob/v0.29.3/tools/cache/expiration_cache.go) you linked earlier looks like a good start. We can check if `CreateNetworkInterface` fails due to missing security group and update the cache, and retry the branch ENI creation. 

Can you also add integration tests? This can be in a follow up PR.

**Comment by GnatorX** [comment]
PR to merge into feature branch https://github.com/aws/amazon-vpc-resource-controller-k8s/pull/410

**Comment by sushrk** [comment]
Oh, it should be possible to just update the base branch in same PR, let me do that.

**Comment by GnatorX** [comment]
Oh sorry. Didn't realize i could update it.

**Comment by sushrk** [comment]
Closing in favor of #410

**Pull request closed without merging**
