### PR TITLE
add/update instance type for sgp/windows

### PR DESCRIPTION
**Pull request by abhipth**
*Issue #, if available:* #87 and #91

*Description of changes:* 
- Update the Branch ENI and Windows IPv4 Address Limits.

*Testing Performed*
The changes can be categorized into multiple buckets. Spot checked a couple of instance types and verified the maximum number of Branch ENIs that can be created.

1. New Instance Types - Tested one instance from different families - c6a.12xlarge, c6i.12xlarge, m6a.16xlarge, r6i.12xlarge, x2iezn.12xlarge
2. Branch ENI Limit Increase - Tested with - d3.4xlarge, r5.metal
3. Previously Unsupported, Now Supported - Tested with g4ad.16xlarge, i3.metal, m5zn.12xlarge
4. Reduced Number of Branch ENIs - Looks like previously were provided with wrong values and the current value seem accurate - Tested with i3en.12xlarge, d3en.xlarge

Callouts
vt1.24xlarge - Seems to not work due to IMDS issues. No issues with allocation of Branch ENI from vpc-resource-controller. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by M00nF1sh — APPROVED** [review]
/lgtm

**Review by jayanthvn — APPROVED** [review]
lgtm, maybe we can add a workflow in cni repo to update this repo when new instance is added?

**Comment by abhipth** [comment]
> lgtm, maybe we can add a workflow in cni repo to update this repo when new instance is added?

Unfortunately this is a manual step as of now because we don't have the Branch ENI limits publicly available.

**Comment by jayanthvn** [comment]
> > lgtm, maybe we can add a workflow in cni repo to update this repo when new instance is added?
> 
> Unfortunately this is a manual step as of now because we don't have the Branch ENI limits publicly available.

Ahh ok.

**Comment by abhipth** [comment]
This is strange the integration tests have been failing continuously, I suspect it has to do with the recent changes we made with #94

**Pull request merged**
