### PR TITLE
Upgrade ginkgo to v2.3.1

### PR DESCRIPTION
**Pull request by jdn5126**
*Issue #, if available:*
N/A

*Description of changes:*
The purpose of this change is to upgrade the version of ginkgo used by VPC Resource Controller to v2.3.1. This is necessary to resolve issues caused by running a ginkgo CLI client >= 2.3.0 against this repo (this is an incompatibility between versions < 2.3.0 and >= 2.3.0).

The ginkgo issue is described in https://github.com/onsi/ginkgo/issues/1050

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by sushrk — APPROVED** [review]
lgtm

**Review by orsenthil — APPROVED** [review]
LGTM.

**Comment by haouc** [comment]
I will merge this after we merge the reverts for dependencies updates. Thanks, @jdn5126

**Comment by jdn5126** [comment]
Discarding following #141 . Will regenerate

**Pull request closed without merging**
