### PR TITLE
limit file includes networkcards for controller to handle multicards

### PR DESCRIPTION
**Pull request by haouc**
*Issue #, if available:*
#185 
*Description of changes:*
Currently the controller can only support single card since VPC CNI can only support single network card. This file update provides Network cards information to the controller for provisioning interface correctly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jdn5126 — APPROVED** [review]
Does an equivalent VPC CNI change need to be made for this to be taken advantage of?

**Review by orsenthil — APPROVED** [review]
LGTM. Please ensure that the file in vpc-cni repo is the same one too and diff is 0.

**Comment by haouc** [comment]
> Does an equivalent VPC CNI change need to be made for this to be taken advantage of?

@jdn5126 @orsenthil I don't think VPC CNI need to use the same file as this controller uses because CNI maintains its own list of supported types for falling back if the call to EC2 doesn't work.

**Comment by haouc** [comment]
This change is mainly for adding support for multi cards cases. Currently this controller doesn't know if the instance has multiple network cards and how many interfaces per card. This causes controller incorrectly assign interfaces to their available index. After adding these cards metadata in this file, controller will be able to use these info to correctly get index based on card interfaces range. We will need another PR to change the logic how search for index based on this change.

**Pull request merged**
