### PR TITLE
rebased Windows PD feature branch before adding feature flag

### PR DESCRIPTION
**Pull request by jiechen0826**
*Issue #, if available:*

*Description of changes:*
- Rebased on master branch before adding feature flag

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by haouc** [comment]
Looks like there are conflicts need to be resolved. Can you take a look? Thanks.

**Comment by jiechen0826** [comment]
> Looks like there are conflicts need to be resolved. Can you take a look? Thanks.

Sorry about that. I fixed the conflicts again on the online editor since they didn't show up locally.

**Comment by haouc** [comment]
@jiechen0826 I have approved and merged the other PRs against the feature branch. Can you check if this PR need update accordingly? Thanks.

**Comment by jiechen0826** [comment]
> @jiechen0826 I have approved and merged the other PRs against the feature branch. Can you check if this PR need update accordingly? Thanks.

I rebased again, thanks a lot!

**Comment by haouc** [comment]
Thanks for rebasing those commits. Looks good to me. Let's merge to master and do full tests to make sure no regression and the new feature works.

**Review by haouc — APPROVED** [review]

**Pull request merged**
