### PR TITLE
Update VPC CNI version dependency

### PR DESCRIPTION
**Pull request by jdn5126**
*Issue #, if available:*
N/A

*Description of changes:*
This PR updates the `github.com/aws/amazon-vpc-cni-k8s` version to the latest available, `v1.12.1`. The rest of the changes are from `go mod tidy`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by haouc — APPROVED** [review]
Looks good to me.

**Comment by haouc** [comment]
Let's hold on merge yet. I am checking why unit test is failing.

**Comment by jdn5126** [comment]
> > Details
> 
> > Let's hold on merge yet. I am checking why build and unit test are failing.
> 
> Strange, I ran these locally and they worked fine. From a bit on investigating, it seems that the problem is with `go.mod` and the workflows using go version `1.16`. It's good that we caught this now, as I was planning to bring VPC RC dependencies on k8s and controller-runtime libs up to date with VPC CNI versions next, and those require at least go 1.18 (CNI uses 1.18)



> > Details
> 
> > Let's hold on merge yet. I am checking why build and unit test are failing.
> 
> Strange, I ran these locally and they worked fine. From a bit on investigating, it seems that the problem is with `go.mod` and the workflows using go version `1.16`. It's good that we caught this now, as I was planning to bring VPC RC dependencies on k8s and controller-runtime libs up to date with VPC CNI versions next, and those require at least go 1.18 (CNI uses 1.18)

If it is easier, I can do all of the dependency changes in one PR. Any thoughts on that? I'll make sure that I run the integration tests.

**Comment by jdn5126** [comment]
Closing in order to put up a more thorough version update PR later

**Pull request closed without merging**
